backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "statue"
    label: "Le mie Statue"
    folder: "content/statue"
    create: true
    extension: "json" # Fondamentale: salva come .json
    format: "json"    # Fondamentale: usa il formato JSON
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Immagine", name: "image", widget: "image" }
      - { label: "Descrizione", name: "desc", widget: "text" }
