backend:
  name: git-gateway
  branch: main # Assicurati che sia il nome del tuo branch su GitHub

media_folder: "img/uploads" # Dove verranno salvate le foto delle statue
public_folder: "/img/uploads"

collections:
  - name: "statue"
    label: "Le mie Statue"
    folder: "content/statue" # Qui verranno salvati i dati di ogni statua
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo Opera", name: "title", widget: "string" }
      - { label: "Data Creazione", name: "date", widget: "datetime" }
      - { label: "Foto Principale", name: "image", widget: "image" }
      - { label: "Descrizione", name: "body", widget: "markdown" }
      - { label: "Prezzo (opzionale)", name: "price", widget: "number", required: false }